version: '2'
services:
  chef-resources:
    build: ./
    restart: always
    network_mode: "host"
    container_name: "chef-resources"
    ports:
    - "8082:80"
    volumes:
    - 'webdata:/var/www/html'

volumes:
  webdata: