version: '2'
services:
  chef-resources:
    build: ./
    restart: always
    container_name: "chef-resources"
    ports:
    - "8080:80"
    volumes:
    - 'webdata:/var/www/html'

volumes:
  webdata:
